version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: ../for_devs/env.for_dev
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ./frontend/:/app/result_build/

  backend:
    container_name: foodgram-back
    build: ../backend
    env_file: ../for_devs/env.for_dev
    volumes:
      - static:/app/collected_static/
      - media:/app/media/
    depends_on:
      - db

  nginx:
    container_name: foodgram-gateway
    image: nginx:1.22.1
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - db
      - backend
      - frontend
