MAX_LENGHT_TAG_NAME = 200
MAX_LENGHT_INGREDIENT_NAME = 200
MAX_LENGHT_RECIPE_NAME = 200
MAX_LENGHT_HEX = 7
MAX_LENGHT_SLUG = 200
MAX_LENGHT_MEASUREMENT_UNIT = 200
MIN_COOCKING_TIME = 1
MIN_AMOUNT = 1

MAX_LENGHT_EMAIL = 254
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGHT_LAST_NAME = 150

DOWNLOAD_FILENAME = 'shopping_cart.pdf'
